In [52]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix
from scipy.sparse.csgraph import connected_components, dijkstra, floyd_warshall, bellman_ford, depth_first_order, breadth_first_order

In [53]:
arr= np.array(
    [[0, 0, -3],
     [4, 0, 0],
     [0, 5, 6]]
)

new_array= csr_matrix(arr)

print("Compressed Sparse Row Matrix:\n", new_array)

print("\n",connected_components(new_array))

Compressed Sparse Row Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	-3
  (1, 0)	4
  (2, 1)	5
  (2, 2)	6

 (1, array([0, 0, 0], dtype=int32))


In [54]:
print(dijkstra(new_array, return_predecessors=True, indices=0))

(array([ 0.,  2., -3.]), array([-9999,     2,     0], dtype=int32))


C:\Users\Dhanasekar Murugesan\AppData\Local\Temp\ipykernel_5156\464220825.py:1: UserWarning: Graph has negative weights: dijkstra will give inaccurate results if the graph contains negative cycles. Consider johnson or bellman_ford.
  print(dijkstra(new_array, return_predecessors=True, indices=0))


In [55]:
print(floyd_warshall(new_array, return_predecessors=True))

(array([[ 0.,  2., -3.],
       [ 4.,  0.,  1.],
       [ 9.,  5.,  0.]]), array([[-9999,     2,     0],
       [    1, -9999,     0],
       [    1,     2, -9999]], dtype=int32))


In [56]:
print(bellman_ford(new_array, return_predecessors=True, indices=0))

(array([ 0.,  2., -3.]), array([-9999,     2,     0], dtype=int32))


In [62]:


print(depth_first_order(new_array, 0, return_predecessors=True))

(array([0, 2, 1], dtype=int32), array([-9999,     2,     0], dtype=int32))


In [61]:
print(breadth_first_order(new_array, 0, return_predecessors=True))

(array([0, 2, 1], dtype=int32), array([-9999,     2,     0], dtype=int32))
