In [2]:
import numpy as np


In [12]:
#Simple Arithmetic Operations using ufuncs

arr1=[2,4,6,8]
arr2=[3,5,7,9]

add= np.add(arr1,arr2)
print(add)

sub= np.subtract(arr1,arr2)
print(sub)

mul= np.multiply(arr1,arr2)
print(mul)

div= np.divide(arr1,arr2)
print(div)

exp = np.power(arr1, arr2)
print(exp)

floor_div = np.floor_divide(arr1, arr2)
print(floor_div)

#OR

def task(a,b):
    return a+b, a-b, a*b, a/b, a**b, a//b
mytask= np.frompyfunc(task, 2, 6)
print("\nEverything in one code:\n",mytask(arr1, arr2))

[ 5  9 13 17]
[-1 -1 -1 -1]
[ 6 20 42 72]
[0.66666667 0.8        0.85714286 0.88888889]
[        8      1024    279936 134217728]
[0 0 0 0]

Everything in one code:
 (array([5, 9, 13, 17], dtype=object), array([-1, -1, -1, -1], dtype=object), array([6, 20, 42, 72], dtype=object), array([0.6666666666666666, 0.8, 0.8571428571428571, 0.8888888888888888],
      dtype=object), array([8, 1024, 279936, 134217728], dtype=object), array([0, 0, 0, 0], dtype=object))
