In [1]:
import numpy as np


In [ ]:
#Simple Arithmetic Operations using ufuncs

arr1=[2,4,6,8]
arr2=[3,5,7,9]

add= np.add(arr1,arr2)
print(add)

sub= np.subtract(arr1,arr2)
print(sub)

mul= np.multiply(arr1,arr2)
print(mul)

div= np.divide(arr1,arr2)
print(div)

exp = np.power(arr1, arr2)
print(exp)

floor_div = np.floor_divide(arr1, arr2)
print(floor_div)

#or

def task(a,b):
    return a+b, a-b, a*b, a/b, a**b, a//b
mytask= np.frompyfunc(task, 2, 6)
print("\nEverything in one code:\n",mytask(arr1, arr2))

[ 5  9 13 17]
[-1 -1 -1 -1]
[ 6 20 42 72]
[0.66666667 0.8        0.85714286 0.88888889]
[        8      1024    279936 134217728]
[0 0 0 0]

Everything in one code:
 (array([5, 9, 13, 17], dtype=object), array([-1, -1, -1, -1], dtype=object), array([6, 20, 42, 72], dtype=object), array([0.6666666666666666, 0.8, 0.8571428571428571, 0.8888888888888888],
      dtype=object), array([8, 1024, 279936, 134217728], dtype=object), array([0, 0, 0, 0], dtype=object))


In [3]:
#   Ufunc summation

data_array= np.array([[1,2,3],[4,5,6],[7,8,9]])

sum_array= np.sum(data_array, axis=0) 
print("\nSum along columns:\n",sum_array)

sum_array2= np.sum(data_array, axis=1)  
print("\nSum along rows:\n",sum_array2)

new_array= np.cumsum(data_array)
print("\nCumulative sum of elements:\n",new_array)




Sum along columns:
 [12 15 18]

Sum along rows:
 [ 6 15 24]

Cumulative sum of elements:
 [ 1  3  6 10 15 21 28 36 45]


In [9]:
num_array= np.array([1,2,3,4,5])

result= np.prod(num_array)
print("\nProduct of all elements:",result)

axis_array= np.prod(data_array, axis=0)
print("\nProduct along columns:\n",axis_array)


product_array= np.cumprod(num_array)
print("\nCumulative product of elements:\n",product_array)


Product of all elements: 120

Product along columns:
 [ 28  80 162]

Cumulative product of elements:
 [  1   2   6  24 120]
