In [13]:
import numpy as np 

ZERO=np.zeros((3,4))
print("Array of Zeros:\n", ZERO)

ONE=np.ones((2,3,4),dtype=np.int16) 
print("\nArray of Ones:\n", ONE)

#Empty Array
EMPTY=np.empty((2,3))
print("\nEmpty Array:\n", EMPTY)

#Array of Random Numbers
RANDOM=np.random.random((2,2))
print("\nArray of Random Numbers:\n", RANDOM)

#Array of Sequential Numbers
SEQUENCE=np.arange(10,25,5)
print("\nArray of Sequential Numbers:\n", SEQUENCE)


Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

Empty Array:
 [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]

Array of Random Numbers:
 [[0.42663271 0.2996966 ]
 [0.26404866 0.41124017]]

Array of Sequential Numbers:
 [10 15 20]


In [8]:
#Array of Evenly Spaced Numbers
EVENLY_SPACED=np.linspace(0,2,9)
print("\nArray of Evenly Spaced Numbers:\n", EVENLY_SPACED)

#Identity Matrix
IDENTITY=np.eye(3)
print("\nIdentity Matrix:\n", IDENTITY)

#Array with Custom Values
CUSTOM=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("\nArray with Custom Values:\n", CUSTOM)

#Data Type Conversion
arr=np.array([1,2,3,4,5])
print("\nOriginal Array Data Type:", arr.dtype)

arr_float=arr.astype(np.float64)
print("Converted Array Data Type:", arr_float.dtype)
print("Converted Array:", arr_float)

#Array with Complex Numbers
complex_arr=np.array([1,2,3,4],dtype=complex)
print("\nArray with Complex Numbers:\n", complex_arr)

#Structured Array
structured_arr=np.array([(1,'Alice',25),(2,'Bob',30),(3,'Charlie',35)],
                        dtype=[('ID', 'i4'), ('Name', 'U10'), ('Age', 'i4')])
print("\nStructured Array:\n", structured_arr)
print("Accessing Structured Array Elements:")
print("Names:", structured_arr['Name'])
print("Ages:", structured_arr['Age'])



Array of Evenly Spaced Numbers:
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array with Custom Values:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Original Array Data Type: int64
Converted Array Data Type: float64
Converted Array: [1. 2. 3. 4. 5.]

Array with Complex Numbers:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]

Structured Array:
 [(1, 'Alice', 25) (2, 'Bob', 30) (3, 'Charlie', 35)]
Accessing Structured Array Elements:
Names: ['Alice' 'Bob' 'Charlie']
Ages: [25 30 35]


In [17]:
#Type Casting during Array Creation
casted_arr=np.array([1.5,2.3,3.7],dtype=np.int32)
print("\nType Casted Array:\n", casted_arr)
print("Data Type of Casted Array:", casted_arr.dtype)




Type Casted Array:
 [1 2 3]
Data Type of Casted Array: int32


In [ ]:
#Shape Manipulation
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape = (3, 3, 1)
print(arr)

#Understanding Dimensions
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1], [2]], [[3], [4]], [[5], [6]]])
print("Shape of 1D array:", arr_1d.shape)
print("Shape of 2D array:", arr_2d.shape)
print("Shape of 3D array:", arr_3d.shape)


#Boolean Indexing
arr2=np.array([1,2,3,4,5,6,7,8,9])
mask=arr2>3
print("Boolean Indexing:", arr2[mask])

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Shape of 1D array: (6,)
Shape of 2D array: (2, 3)
Shape of 3D array: (3, 2, 1)
Boolean Indexing: [4 5 6 7 8 9]


In [20]:
#Copy --- IGNORE ---
copied_array= arr.copy()
copied_array[0]=100
print("Original Array:", arr)
print("Copied Array:", copied_array)
#Copy --- IGNORE ---



Original Array: [[[100]
  [100]
  [100]]

 [[  4]
  [  5]
  [  6]]

 [[  7]
  [  8]
  [  9]]]
Copied Array: [[[100]
  [100]
  [100]]

 [[  4]
  [  5]
  [  6]]

 [[  7]
  [  8]
  [  9]]]


In [19]:
#View --- IGNORE ---
viewed_array= arr.view()
viewed_array[0]=100
print("Original Array after modifying view:", arr)
print("Viewed Array:", viewed_array)

Original Array after modifying view: [[[100]
  [100]
  [100]]

 [[  4]
  [  5]
  [  6]]

 [[  7]
  [  8]
  [  9]]]
Viewed Array: [[[100]
  [100]
  [100]]

 [[  4]
  [  5]
  [  6]]

 [[  7]
  [  8]
  [  9]]]
